@s-01-usuarios.sql
@s-02-entidades.sql
@s-03-tablas-temporales.sql
@s-04-tablas-externas.sql
@s-05-secuencias.sql
@s-06-indices.sql
@s-07-sinonimos.sql
@s-08-vistas.sql
@s-09-carga-inicial.sql
@s-10-consultas.sql
@s-11-tr-pedido_medicamento_unidades.sql
@s-12-tr-pedido_medicamento_unidades_prueba.sql
@s-11-tr-pedido_ubicacion.sql
@s-12-tr-pedido_ubicacion_prueba.sql
@s-13-p-crea_actualiza_pedido.sql
@s-14-p-crea_actualiza_pedido-prueba.sql
@s-15-fx-total_almacen.sql
@s-16-fx-total_almacen-prueba.sql