--@Autor(es): Vigi Garduño Marco Alejandro, López Campillo Francisco Daniel
--@Fecha creación: 06/06/2024
--@Descripción: Carga inicial de los datos para la base de datos

Prompt conectando con el admin
connect vl_proy_admin/proyecto

Prompt ingresando datos a la tabla cliente
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Francisco Daniel', 'López', 'Campillo', 'lopezfr24@gmail.com', 5598504785, 'LCFDMDF874526', null, 'Calle palenque 204 av iman colonia narvarte, Ciudad de México, México');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Marco Alejandro', 'Vigi', 'Garduño', 'vigiale3242@gmail.com', 5598784589, 'VIGM879852658', null, 'Naucalpan de juarez, Estado de México, México.');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Bernardo', 'Reubens', 'Lynock', 'blynock0@comcast.net', 6501922458, 'F7TRP64Z91E3K', 'KLDD761874MCPTRS91', '18 Lunder Plaza');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Julianne', 'Chew', 'Prisk', 'jprisk1@irs.gov', 1272077833, '56M8SG1YM9PQ8', 'CMAY998630MRRMXQ69', '22 Village Green Lane');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Sallyann', 'Heys', 'Brandom', 'sbrandom2@weibo.com', 9287325646, '82C0F35542R5K', 'RMRL825379HBFIIK20', '962 Oak Park');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Brocky', 'Oulett', 'Curuclis', 'bcuruclis3@homestead.com', 9487268213, '881056YTO9RP0', 'FICR690299HJSXGW78', '7264 Melrose Drive');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Ibbie', 'Kew', 'Haryngton', 'iharyngton4@mediafire.com', 2714419935, '982Z0Q8252NV9', 'EYFY165284HMALTZ38', '58 Northview Point');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Deeanne', 'Vallentine', 'Gladdis', 'dgladdis5@tripod.com', 9680688727, '1TY98ZI5OWQKN', 'FADZ485377HIORFD89', '0 Hauk Street');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Francine', 'Pierce', 'Ernke', 'fernke6@usatoday.com', 3600803343, '2F1U2A02N650R', 'SFIX996305MYXIWT41', '4947 Clemons Court');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Ferdie', 'Arndell', 'Boothe', 'fboothe7@yandex.ru', 401411597, 'G5ITSKY7JN9M5', 'VUGR469102MRSUCU76', '258 Towne Road');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Trenna', 'Hickisson', 'De Filippi', 'tdefilippi8@elegantthemes.com', 5983868162, 'SL1348F9ZKCI0', 'VYMB729837HOOBEI46', '3 Autumn Leaf Court');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Thaddus', 'Shermar', 'Bea', 'tbea9@google.co.jp', 3126157927, '6654Q35C8PB19', 'UXJD954776MRKGDJ05', '961 Grasskamp Street');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Rowena', 'Edgin', 'Child', 'rchilda@yandex.ru', 7799633804, 'IV488T5OYIYCR', 'WWGA165461HHSWGC30', '48334 Anniversary Place');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Shaine', 'Oertzen', 'Franseco', 'sfransecob@mac.com', 8733126040, '48E5LGZ2I8919', 'CKNM369241HXDRTL15', '91 Russell Trail');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Gussie', 'Coper', 'Kordova', 'gkordovac@imdb.com', 5254125713, '6UKX94WDQ3100', 'KZEJ731868HISBRM02', '9272 Colorado Circle');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Adella', 'Redolfi', 'Bigadike', 'abigadiked@1und1.de', 1059404375, 'FXIN2877Y999P', 'SZLW022296HKZTMG75', '26 Mockingbird Road');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Benedict', 'Caris', 'Heinish', 'bheinishe@ftc.gov', 4099604531, 'R5GX73XG47YPS', 'OFMR744687MXQZUU52', '96574 Hooker Way');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Josh', 'Rubinshtein', 'Lear', 'jlearf@angelfire.com', 3582028585, 'SZ723NRD4PJ94', 'TLVL744242HJZEAQ27', '2 Commercial Lane');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Nathanial', 'Wimmers', 'Draaisma', 'ndraaismag@sitemeter.com', 9543434745, 'O14V9312X1OQ1', 'VCAN339833MJAMBL28', '8199 Ridge Oak Pass');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Patton', 'Goff', 'Quakley', 'pquakleyh@theatlantic.com', 9900863783, 'N6RPF1PH14516', 'ICOI921385MNQUDQ62', '6499 Crest Line Trail');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Janith', 'Goligher', 'Bowerbank', 'jbowerbanki@bloglines.com', 9511430215, 'G4Q153HPI98S0', 'BCIE259728MTEYZW60', '968 Meadow Vale Center');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Obadiah', 'Lawther', 'Kembrey', 'okembreyj@wisc.edu', 9569288618, '9CX89TF9UT440', 'OLMY918896MRTHKQ28', '019 Paget Terrace');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Dorisa', 'Moreinis', 'Jackways', 'djackwaysk@msn.com', 2784094103, 'LLV25IMD953H6', 'AUYO839321MZKADK79', '4736 Weeping Birch Parkway');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Dayle', 'Costard', 'Crosbie', 'dcrosbiel@dmoz.org', 3040832619, 'HL9IKSZX4446W', 'EMIQ254373HWKIZD33', '5 Forest Run Avenue');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Constantino', 'Challinor', 'Dolman', 'cdolmanm@soup.io', 270591353, '15KV43ZBKP9U3', 'FZNK233181MCPEWS74', '121 Graceland Court');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Sybila', 'Kleingrub', 'von Hagt', 'svonhagtn@digg.com', 2815627494, 'ML92IK4PBY75I', 'GLVL693344HHQJRK15', '5400 Rigney Avenue');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Rickert', 'Prangle', 'McBride', 'rmcbrideo@hatena.ne.jp', 1098906372, 'D7Q2VOD8CBJZU', 'JPLN336635MLMSIO07', '6 Lillian Junction');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Johnathon', 'Roycroft', 'Bramhill', 'jbramhillp@omniture.com', 3957055137, 'C16RNXCQS2IVN', 'NQPC027170HGZQNS64', '0 Cordelia Place');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Lilith', 'O''Nions', 'Malzard', 'lmalzardq@dropbox.com', 1872740651, 'W45HO710XLZI5', 'DXNT696844HMLEYH64', '908 Novick Crossing');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Reagan', 'Stocks', 'Tortoishell', 'rtortoishellr@cam.ac.uk', 3480789544, '52HQ253TP3P33', 'ZVUL823619HCTNVB19', '8 Coolidge Park');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Diane-marie', 'Jemison', 'Cleynaert', 'dcleynaerts@zimbio.com', 7683759033, '568R58JRI3SC9', 'WDSI987458MXLNKV37', '939 Holy Cross Way');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Jaynell', 'Phinnessy', 'Sancraft', 'jsancraftt@devhub.com', 2311287310, '2LUFAIG7BYY0S', 'OJOU529641MYUULK42', '47066 Leroy Park');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Laurence', 'Cornels', 'Bootyman', 'lbootymanu@acquirethisname.com', 7013498494, 'TYW0MU9T6W28Q', 'JOIU706202HEXUAY82', '54 Tony Pass');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Gizela', 'O''Hern', 'Alldis', 'galldisv@wordpress.com', 5753514535, 'ZCKN78OU1R33A', 'JYIF835142HFPYTL70', '6020 Gerald Alley');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Domeniga', 'Fenny', 'Gush', 'dgushw@sourceforge.net', 1925858297, 'E80W50VWJG96N', 'YXNW414998HEQOAB19', '10 Milwaukee Pass');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Faustine', 'Handke', 'Calbrathe', 'fcalbrathex@skyrock.com', 3715923450, 'EL836D2WI9604', 'OAJQ029591MBORWL14', '195 Delladonna Parkway');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Leslie', 'Stodhart', 'Petyankin', 'lpetyankiny@istockphoto.com', 5889888674, '4TNPQB7HW62ZS', 'BWDT176425MLAMYW01', '68472 8th Pass');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Kati', 'Durrett', 'Crosi', 'kcrosiz@trellian.com', 5350251246, 'J617KF1K0UZ44', 'YVEU998952MMKTHT86', '15 Village Green Alley');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Shaina', 'Camelin', 'Djokic', 'sdjokic10@de.vu', 822366773, 'OEX1V0I1D2L8H', 'VYKM080416MUIVZO51', '00 Sherman Parkway');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Charles', 'Wilde', 'Sprakes', 'csprakes11@seattletimes.com', 8268173063, 'MJ5DIL9JSOXNP', 'JTJZ504981HDQWSG23', '72 Hoffman Way');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Corrie', 'Ruddy', 'Reddan', 'creddan12@tinypic.com', 1758373054, 'RBOJ61NU0351S', 'OKEA615584HAUEHZ77', '7849 Anthes Junction');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Juliet', 'Gerardin', 'Bulstrode', 'jbulstrode13@examiner.com', 1657962913, '8PY5R5JO4IF49', 'AEBX600462HKWSTU36', '6843 Prairieview Alley');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Cammy', 'Leggan', 'Eiler', 'ceiler14@gnu.org', 8192350172, 'U9RR2WLC0924Y', 'EKPH014875HZSUAX29', '16 Cody Drive');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Aggi', 'Sellen', 'Gillings', 'agillings15@ycombinator.com', 6555012767, '9PVU1GY0OQR08', 'UJRG330409MDTAJH36', '9730 Birchwood Alley');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Sheryl', 'Hakking', 'Gue', 'sgue16@amazonaws.com', 1590063752, '8B17X74Y1Y8B2', 'FSBG961590HHGKSA45', '17471 Elka Avenue');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Enoch', 'Boggis', 'Patten', 'epatten17@pagesperso-orange.fr', 4694801504, '1FJ205B2G3VG1', 'CNIX147829MXSYTC94', '4 Monument Center');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Fara', 'Dornin', 'Caines', 'fcaines18@toplist.cz', 4685303994, 'EF8W3J43KFZEZ', 'RCAW505891HTQYAD35', '472 Springs Way');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'De witt', 'Newbury', 'Ewington', 'dewington19@time.com', 9391722114, '9H3I0T248G1S6', 'IILC394359MHMAMD02', '14415 Lake View Drive');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Theodore', 'Brisbane', 'Tayspell', 'ttayspell1a@go.com', 2028679843, 'KLO0O8B1M1428', 'LFLD362523MIJLSH52', '2552 Manley Parkway');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Aida', 'Fortin', 'Dutt', 'adutt1b@dot.gov', 7065653895, '907Z6PQ4134J1', 'POHI835245HXBDIG31', '82 Kipling Street');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Sam', 'Canner', 'Longstaffe', 'slongstaffe1c@reuters.com', 8989896197, '9VSDUU804DLIE', 'EJMA864761MTIIHW56', '56 Northland Circle');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Alissa', 'Warlowe', 'McLaverty', 'amclaverty1d@woothemes.com', 1564150983, '7P7G38Y569B06', 'HBEF123894MNGQBG98', '5755 Declaration Alley');

