--@Autor(es): Vigi Garduño Marco Alejandro, López Campillo Francisco Daniel
--@Fecha creación: 06/06/2024
--@Descripción: Carga inicial de los datos para la base de datos

Prompt conectando con el admin
connect vl_proy_admin/proyecto

Prompt ingresando datos a la tabla cliente
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Francisco Daniel', 'López', 'Campillo', 'lopezfr24@gmail.com', 5598504785, 'LCFDMDF874526', null, 'Calle palenque 204 av iman colonia narvarte, Ciudad de México, México');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Marco Alejandro', 'Vigi', 'Garduño', 'vigiale3242@gmail.com', 5598784589, 'VIGM879852658', null, 'Naucalpan de juarez, Estado de México, México.');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Bernardo', 'Reubens', 'Lynock', 'blynock0@comcast.net', 6501922458, 'F7TRP64Z91E3K', 'KLDD761874MCPTRS91', '18 Lunder Plaza');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Julianne', 'Chew', 'Prisk', 'jprisk1@irs.gov', 1272077833, '56M8SG1YM9PQ8', 'CMAY998630MRRMXQ69', '22 Village Green Lane');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Sallyann', 'Heys', 'Brandom', 'sbrandom2@weibo.com', 9287325646, '82C0F35542R5K', 'RMRL825379HBFIIK20', '962 Oak Park');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Brocky', 'Oulett', 'Curuclis', 'bcuruclis3@homestead.com', 9487268213, '881056YTO9RP0', 'FICR690299HJSXGW78', '7264 Melrose Drive');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Ibbie', 'Kew', 'Haryngton', 'iharyngton4@mediafire.com', 2714419935, '982Z0Q8252NV9', 'EYFY165284HMALTZ38', '58 Northview Point');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Deeanne', 'Vallentine', 'Gladdis', 'dgladdis5@tripod.com', 9680688727, '1TY98ZI5OWQKN', 'FADZ485377HIORFD89', '0 Hauk Street');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Francine', 'Pierce', 'Ernke', 'fernke6@usatoday.com', 3600803343, '2F1U2A02N650R', 'SFIX996305MYXIWT41', '4947 Clemons Court');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Ferdie', 'Arndell', 'Boothe', 'fboothe7@yandex.ru', 401411597, 'G5ITSKY7JN9M5', 'VUGR469102MRSUCU76', '258 Towne Road');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Trenna', 'Hickisson', 'De Filippi', 'tdefilippi8@elegantthemes.com', 5983868162, 'SL1348F9ZKCI0', 'VYMB729837HOOBEI46', '3 Autumn Leaf Court');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Thaddus', 'Shermar', 'Bea', 'tbea9@google.co.jp', 3126157927, '6654Q35C8PB19', 'UXJD954776MRKGDJ05', '961 Grasskamp Street');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Rowena', 'Edgin', 'Child', 'rchilda@yandex.ru', 7799633804, 'IV488T5OYIYCR', 'WWGA165461HHSWGC30', '48334 Anniversary Place');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Shaine', 'Oertzen', 'Franseco', 'sfransecob@mac.com', 8733126040, '48E5LGZ2I8919', 'CKNM369241HXDRTL15', '91 Russell Trail');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Gussie', 'Coper', 'Kordova', 'gkordovac@imdb.com', 5254125713, '6UKX94WDQ3100', 'KZEJ731868HISBRM02', '9272 Colorado Circle');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Adella', 'Redolfi', 'Bigadike', 'abigadiked@1und1.de', 1059404375, 'FXIN2877Y999P', 'SZLW022296HKZTMG75', '26 Mockingbird Road');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Benedict', 'Caris', 'Heinish', 'bheinishe@ftc.gov', 4099604531, 'R5GX73XG47YPS', 'OFMR744687MXQZUU52', '96574 Hooker Way');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Josh', 'Rubinshtein', 'Lear', 'jlearf@angelfire.com', 3582028585, 'SZ723NRD4PJ94', 'TLVL744242HJZEAQ27', '2 Commercial Lane');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Nathanial', 'Wimmers', 'Draaisma', 'ndraaismag@sitemeter.com', 9543434745, 'O14V9312X1OQ1', 'VCAN339833MJAMBL28', '8199 Ridge Oak Pass');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Patton', 'Goff', 'Quakley', 'pquakleyh@theatlantic.com', 9900863783, 'N6RPF1PH14516', 'ICOI921385MNQUDQ62', '6499 Crest Line Trail');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Janith', 'Goligher', 'Bowerbank', 'jbowerbanki@bloglines.com', 9511430215, 'G4Q153HPI98S0', 'BCIE259728MTEYZW60', '968 Meadow Vale Center');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Obadiah', 'Lawther', 'Kembrey', 'okembreyj@wisc.edu', 9569288618, '9CX89TF9UT440', 'OLMY918896MRTHKQ28', '019 Paget Terrace');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Dorisa', 'Moreinis', 'Jackways', 'djackwaysk@msn.com', 2784094103, 'LLV25IMD953H6', 'AUYO839321MZKADK79', '4736 Weeping Birch Parkway');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Dayle', 'Costard', 'Crosbie', 'dcrosbiel@dmoz.org', 3040832619, 'HL9IKSZX4446W', 'EMIQ254373HWKIZD33', '5 Forest Run Avenue');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Constantino', 'Challinor', 'Dolman', 'cdolmanm@soup.io', 270591353, '15KV43ZBKP9U3', 'FZNK233181MCPEWS74', '121 Graceland Court');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Sybila', 'Kleingrub', 'von Hagt', 'svonhagtn@digg.com', 2815627494, 'ML92IK4PBY75I', 'GLVL693344HHQJRK15', '5400 Rigney Avenue');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Rickert', 'Prangle', 'McBride', 'rmcbrideo@hatena.ne.jp', 1098906372, 'D7Q2VOD8CBJZU', 'JPLN336635MLMSIO07', '6 Lillian Junction');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Johnathon', 'Roycroft', 'Bramhill', 'jbramhillp@omniture.com', 3957055137, 'C16RNXCQS2IVN', 'NQPC027170HGZQNS64', '0 Cordelia Place');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Lilith', 'O''Nions', 'Malzard', 'lmalzardq@dropbox.com', 1872740651, 'W45HO710XLZI5', 'DXNT696844HMLEYH64', '908 Novick Crossing');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Reagan', 'Stocks', 'Tortoishell', 'rtortoishellr@cam.ac.uk', 3480789544, '52HQ253TP3P33', 'ZVUL823619HCTNVB19', '8 Coolidge Park');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Diane-marie', 'Jemison', 'Cleynaert', 'dcleynaerts@zimbio.com', 7683759033, '568R58JRI3SC9', 'WDSI987458MXLNKV37', '939 Holy Cross Way');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Jaynell', 'Phinnessy', 'Sancraft', 'jsancraftt@devhub.com', 2311287310, '2LUFAIG7BYY0S', 'OJOU529641MYUULK42', '47066 Leroy Park');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Laurence', 'Cornels', 'Bootyman', 'lbootymanu@acquirethisname.com', 7013498494, 'TYW0MU9T6W28Q', 'JOIU706202HEXUAY82', '54 Tony Pass');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Gizela', 'O''Hern', 'Alldis', 'galldisv@wordpress.com', 5753514535, 'ZCKN78OU1R33A', 'JYIF835142HFPYTL70', '6020 Gerald Alley');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Domeniga', 'Fenny', 'Gush', 'dgushw@sourceforge.net', 1925858297, 'E80W50VWJG96N', 'YXNW414998HEQOAB19', '10 Milwaukee Pass');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Faustine', 'Handke', 'Calbrathe', 'fcalbrathex@skyrock.com', 3715923450, 'EL836D2WI9604', 'OAJQ029591MBORWL14', '195 Delladonna Parkway');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Leslie', 'Stodhart', 'Petyankin', 'lpetyankiny@istockphoto.com', 5889888674, '4TNPQB7HW62ZS', 'BWDT176425MLAMYW01', '68472 8th Pass');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Kati', 'Durrett', 'Crosi', 'kcrosiz@trellian.com', 5350251246, 'J617KF1K0UZ44', 'YVEU998952MMKTHT86', '15 Village Green Alley');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Shaina', 'Camelin', 'Djokic', 'sdjokic10@de.vu', 822366773, 'OEX1V0I1D2L8H', 'VYKM080416MUIVZO51', '00 Sherman Parkway');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Charles', 'Wilde', 'Sprakes', 'csprakes11@seattletimes.com', 8268173063, 'MJ5DIL9JSOXNP', 'JTJZ504981HDQWSG23', '72 Hoffman Way');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Corrie', 'Ruddy', 'Reddan', 'creddan12@tinypic.com', 1758373054, 'RBOJ61NU0351S', 'OKEA615584HAUEHZ77', '7849 Anthes Junction');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Juliet', 'Gerardin', 'Bulstrode', 'jbulstrode13@examiner.com', 1657962913, '8PY5R5JO4IF49', 'AEBX600462HKWSTU36', '6843 Prairieview Alley');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Cammy', 'Leggan', 'Eiler', 'ceiler14@gnu.org', 8192350172, 'U9RR2WLC0924Y', 'EKPH014875HZSUAX29', '16 Cody Drive');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Aggi', 'Sellen', 'Gillings', 'agillings15@ycombinator.com', 6555012767, '9PVU1GY0OQR08', 'UJRG330409MDTAJH36', '9730 Birchwood Alley');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Sheryl', 'Hakking', 'Gue', 'sgue16@amazonaws.com', 1590063752, '8B17X74Y1Y8B2', 'FSBG961590HHGKSA45', '17471 Elka Avenue');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Enoch', 'Boggis', 'Patten', 'epatten17@pagesperso-orange.fr', 4694801504, '1FJ205B2G3VG1', 'CNIX147829MXSYTC94', '4 Monument Center');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Fara', 'Dornin', 'Caines', 'fcaines18@toplist.cz', 4685303994, 'EF8W3J43KFZEZ', 'RCAW505891HTQYAD35', '472 Springs Way');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'De witt', 'Newbury', 'Ewington', 'dewington19@time.com', 9391722114, '9H3I0T248G1S6', 'IILC394359MHMAMD02', '14415 Lake View Drive');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Theodore', 'Brisbane', 'Tayspell', 'ttayspell1a@go.com', 2028679843, 'KLO0O8B1M1428', 'LFLD362523MIJLSH52', '2552 Manley Parkway');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Aida', 'Fortin', 'Dutt', 'adutt1b@dot.gov', 7065653895, '907Z6PQ4134J1', 'POHI835245HXBDIG31', '82 Kipling Street');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Sam', 'Canner', 'Longstaffe', 'slongstaffe1c@reuters.com', 8989896197, '9VSDUU804DLIE', 'EJMA864761MTIIHW56', '56 Northland Circle');
insert into cliente (cliente_id, nombre, apellido_paterno, apellido_materno, email, telefono, rfc, curp, direccion_envio) values (cliente_seq.nextval, 'Alissa', 'Warlowe', 'McLaverty', 'amclaverty1d@woothemes.com', 1564150983, '7P7G38Y569B06', 'HBEF123894MNGQBG98', '5755 Declaration Alley');

Prompt ingresando datos a la tabla ubicacion
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N9°42''7', 'W41°92''27');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S69°5''44', 'E83°8''53');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S7°0''6', 'W450°38''42');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S6°96''6', 'W3°2''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S33°9''26', 'W82°35''23');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N4°15''9', 'W2°67''19');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N5°01''2', 'W711°4''4');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S55°02''08', 'W186°72''72');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S66°47''1', 'W1°6''4');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N9°23''7', 'E5°8''88');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S15°27''38', 'W40°93''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S7°42''6', 'E9°68''04');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N8°09''6', 'W13°9''9');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N85°8''78', 'E66°7''00');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S09°61''76', 'W87°51''94');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N4°68''8', 'E86°3''63');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N9°21''63', 'W6°39''05');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S58°1''05', 'E0°4''6');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S3°33''25', 'W5°72''4');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S8°99''1', 'E368°23''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S9°6''9', 'E35°6''64');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N9°68''97', 'W93°16''58');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S83°41''24', 'E187°7''2');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S92°6''95', 'E018°28''6');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S10°1''44', 'E37°4''3');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S28°24''0', 'E00°01''90');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S70°6''87', 'E55°1''7');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N5°81''79', 'W3°48''2');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S63°92''99', 'E1°7''52');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N65°91''43', 'E1°31''7');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S33°03''9', 'E0°87''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S7°0''16', 'W725°2''9');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S9°90''78', 'E5°32''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N6°20''62', 'W443°9''31');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S3°62''2', 'E97°1''50');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N99°67''5', 'W6°51''4');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N43°3''82', 'E755°7''16');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N1°2''00', 'W22°8''83');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S1°29''0', 'W08°9''1');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S45°2''8', 'W1°19''32');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S5°0''07', 'W577°0''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N54°15''3', 'E533°42''86');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N1°36''90', 'E41°6''10');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S0°55''1', 'W272°0''9');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N17°5''89', 'E5°74''56');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N08°7''0', 'W6°66''24');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S56°2''4', 'W4°93''72');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N79°38''26', 'W1°2''9');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S1°6''0', 'W80°6''18');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N2°7''31', 'E0°2''53');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N12°41''62', 'E0°9''3');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S1°6''90', 'W658°6''74');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S32°48''82', 'E447°5''86');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S5°57''4', 'W05°00''64');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N62°13''12', 'E9°3''51');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S59°90''20', 'E002°9''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N26°5''0', 'E1°6''6');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S1°1''9', 'E3°4''20');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S71°5''3', 'E66°66''73');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S96°90''8', 'W9°1''74');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N5°0''55', 'W51°6''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N09°17''8', 'E3°09''7');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S9°7''66', 'W14°73''2');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N50°1''36', 'E006°0''1');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S5°89''34', 'W634°8''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N4°2''3', 'E37°56''3');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S0°3''6', 'W977°5''99');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N31°9''06', 'W2°5''2');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S67°02''4', 'E53°3''4');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N2°5''9', 'E59°7''0');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N6°2''3', 'W731°33''92');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N6°94''9', 'E8°8''7');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S15°0''6', 'E2°47''73');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N67°42''0', 'W3°05''9');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N52°91''43', 'W142°3''20');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N29°1''9', 'E4°57''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S6°52''1', 'E3°8''03');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N9°6''71', 'E4°17''2');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N06°90''20', 'E888°8''45');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S74°6''03', 'E041°84''2');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S85°3''1', 'W165°05''42');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N83°31''10', 'W21°42''4');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N5°74''61', 'W2°16''70');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S75°4''01', 'W49°08''36');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N4°0''3', 'E7°9''29');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N80°4''99', 'W948°56''9');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S0°8''4', 'W2°73''6');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N8°88''97', 'E7°12''8');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N77°29''29', 'E65°74''5');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N24°5''9', 'W9°35''16');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N85°34''19', 'W092°4''8');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S7°74''38', 'W263°2''2');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N4°41''80', 'W098°14''70');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N98°4''98', 'E726°3''61');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S2°0''79', 'W0°71''0');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S4°2''0', 'E8°10''1');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'N65°90''13', 'W9°97''7');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S89°69''54', 'W879°7''82');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S18°57''04', 'W65°7''21');
insert into ubicacion (ubicacion_id, latitud, longitud) values (ubicacion_seq.nextval, 'S46°44''1', 'W054°6''74');

Prompt ingresando datos a la tabla tarjeta
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 9898032459684603, 5, 60, 12);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2740335129013474, 7, 11, 26);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 6637938300060639, 12, 89, 46);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 6558663836673903, 6, 26, 44);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2450841195307442, 11, 11, 17);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 9584603462059702, 5, 95, 28);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2538019826651680, 5, 78, 45);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2486617588389611, 6, 58, 4);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 6738576708561692, 4, 2, 36);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2893368115233290, 4, 40, 44);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 4209835596639903, 8, 48, 7);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 601422642371597, 9, 93, 29);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 1911461441042033, 5, 49, 42);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 6762119436343972, 10, 21, 36);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 4389259172988219, 4, 51, 42);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 6831448781391289, 11, 50, 12);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 9711128070575578, 4, 50, 46);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 3731193138452738, 10, 15, 36);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2569213945201758, 8, 87, 44);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 6683642938068988, 4, 81, 16);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 5865637433827406, 4, 68, 45);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 1539507335845872, 3, 87, 44);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 6125613128254989, 4, 32, 16);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 8441439654049189, 10, 77, 18);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2440024076288171, 6, 41, 29);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2287757746415759, 10, 25, 27);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 8565817364569666, 8, 15, 5);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 4024746120524879, 7, 27, 14);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 1452828033881014, 1, 68, 34);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 5045986730382973, 2, 89, 42);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 9882785081030897, 9, 1, 19);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 1806356857524844, 7, 14, 45);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 8310735409859813, 8, 84, 38);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 5204779567464769, 1, 44, 14);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 5286086923442296, 4, 41, 48);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 6185797454065748, 5, 71, 14);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 2663497915519663, 8, 6, 12);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 4053906317529036, 3, 2, 34);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 1934997640805212, 1, 9, 6);
insert into tarjeta (tarjeta_id, numero_tarjeta, mes_expiracion, anio_expiracion, cliente_id) values (tarjeta_seq.nextval, 1572172683757841, 2, 80, 39);


Prompt ingresando los estados existentes de acuerdo al caso de estudio a la tabla estado_pedido
insert into estado_pedido (estado_pedido_id, clave, descripcion) values (estado_pedido_seq.nextval, 'CAPTURADO', 'El pedido ha sido registrado en el sistema pero aún no ha sido procesado ni enviado.');
insert into estado_pedido (estado_pedido_id, clave, descripcion) values (estado_pedido_seq.nextval, 'EN TRÁNSITO', 'El pedido ha sido procesado y enviado, y se encuentra actualmente en camino hacia su destino.');
insert into estado_pedido (estado_pedido_id, clave, descripcion) values (estado_pedido_seq.nextval, 'ENTREGADO', 'El pedido ha sido entregado satisfactoriamente al cliente.');
insert into estado_pedido (estado_pedido_id, clave, descripcion) values (estado_pedido_seq.nextval, 'DEVUELTO', 'El pedido ha sido devuelto por alguna razón, como un error en la dirección de entrega o la negativa del cliente a aceptarlo.');
insert into estado_pedido (estado_pedido_id, clave, descripcion) values (estado_pedido_seq.nextval, 'CANCELADO', 'El pedido ha sido cancelado debido a la solicitud del cliente o a problemas de disponibilidad de productos.');


Prompt ingresando medicamentos para su tabla correspondiente
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Paracetamol', 'Analgésico y antipirético comúnmente utilizado para tratar el dolor y la fiebre.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Omeprazol', 'Inhibidor de la bomba de protones utilizado para reducir la producción de ácido estomacal.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Loratadina', 'Antihistamínico utilizado para aliviar los síntomas de las alergias.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Amoxicilina', 'Antibiótico utilizado para tratar una variedad de infecciones bacterianas.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Atorvastatina', 'Estatina utilizada para reducir los niveles de colesterol.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Ciprofloxacino', 'Antibiótico de amplio espectro utilizado para tratar diversas infecciones bacterianas.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Metformina', 'Antidiabético oral utilizado para tratar la diabetes tipo 2.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Sertralina', 'Antidepresivo de la clase de los inhibidores selectivos de la recaptación de serotonina.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Ranitidina', 'Antagonista de los receptores H2 utilizado para reducir la producción de ácido estomacal.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Tramadol', 'Analgésico opiáceo utilizado para tratar el dolor moderado a severo.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Diazepam', 'Benzodiacepina utilizada para tratar la ansiedad, los trastornos del sueño y las convulsiones.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Cetirizina', 'Antihistamínico de segunda generación utilizado para tratar las alergias.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Metronidazol', 'Antibiótico y antiprotozoario utilizado para tratar infecciones bacterianas y parasitarias.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Amlodipino', 'Bloqueador de los canales de calcio utilizado para tratar la hipertensión y la angina de pecho.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Fluoxetina', 'Antidepresivo de la clase de los inhibidores selectivos de la recaptación de serotonina.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Clonazepam', 'Benzodiacepina utilizada para tratar los trastornos de ansiedad y las convulsiones.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Levofloxacino', 'Antibiótico de amplio espectro utilizado para tratar diversas infecciones bacterianas.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Losartán', 'Bloqueador del receptor de angiotensina II utilizado para tratar la hipertensión.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Fluconazol', 'Antifúngico utilizado para tratar las infecciones fúngicas, incluida la candidiasis.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Ceftriaxona', 'Antibiótico de amplio espectro utilizado para tratar una variedad de infecciones bacterianas.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Itraconazol', 'Antifúngico utilizado para tratar las infecciones fúngicas, incluida la onicomicosis.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Pantoprazol', 'Inhibidor de la bomba de protones utilizado para reducir la producción de ácido estomacal.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Doxiciclina', 'Antibiótico de tetraciclina utilizado para tratar diversas infecciones bacterianas.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Escitalopram', 'Antidepresivo de la clase de los inhibidores selectivos de la recaptación de serotonina.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Naproxeno', 'Antiinflamatorio no esteroideo utilizado para aliviar el dolor, la fiebre y la inflamación.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Cefalexina', 'Antibiótico de cefalosporina utilizado para tratar diversas infecciones bacterianas.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Hidroclorotiazida', 'Diurético utilizado para tratar la hipertensión y la retención de líquidos.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Budesonida', 'Corticoide inhalado utilizado para tratar el asma y la enfermedad pulmonar obstructiva crónica.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Furosemida', 'Diurético de asa utilizado para tratar la hipertensión y la retención de líquidos.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Alprazolam', 'Benzodiacepina utilizada para tratar los trastornos de ansiedad y el trastorno de pánico.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Carbamazepina', 'Antiepiléptico y estabilizador del estado de ánimo utilizado para tratar la epilepsia y el trastorno bipolar.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Azitromicina', 'Antibiótico macrólido utilizado para tratar una variedad de infecciones bacterianas.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Montelukast', 'Antagonista del receptor de leucotrienos utilizado para tratar el asma y las alergias.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Venlafaxina', 'Antidepresivo de la clase de los inhibidores de la recaptación de serotonina y noradrenalina.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Sulfametoxazol / Trimetoprima', 'Antibiótico combinado utilizado para tratar infecciones bacterianas.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Citalopram', 'Antidepresivo de la clase de los inhibidores selectivos de la recaptación de serotonina.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Prednisona', 'Corticoide utilizado para tratar diversas condiciones inflamatorias y autoinmunes.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Metoclopramida', 'Agonista del receptor de dopamina utilizado para tratar las náuseas y los trastornos de la motilidad gastrointestinal.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Acetaminofén', 'Analgésico y antipirético utilizado para tratar el dolor y la fiebre.');
insert into medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval,'Ibuprofeno', 'Antiinflamatorio no esteroideo utilizado para aliviar el dolor, la fiebre y la inflamación.');



Prompt insertando datos iniciales en tabla nombre_medicamento
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'XL3', 30);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Excedrin', 10);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'NyQuil', 8);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Motrin', 5);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Aleve', 1);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Motrin', 20);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Imodium', 30);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Imodium', 37);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Excedrin', 24);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Excedrin', 32);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Robitussin', 31);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Allegra', 30);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Pepto-Bismol', 20);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Imodium', 30);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Dramamine', 3);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'NyQuil', 17);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Excedrin', 15);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Robitussin', 36);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Robitussin', 38);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Benadryl', 25);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Zantac', 22);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Aleve', 1);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Motrin', 33);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Robitussin', 8);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Sudafed', 39);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Dramamine', 7);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Aleve', 21);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'DayQuil', 39);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Imodium', 34);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'NyQuil', 22);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Dramamine', 10);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Sudafed', 20);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Mucinex', 27);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Allegra', 8);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Pepto-Bismol', 19);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Benadryl', 3);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Pepto-Bismol', 9);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Aleve', 23);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Benadryl', 5);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Aleve', 26);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Sudafed', 3);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Benadryl', 9);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Tums', 11);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Excedrin', 33);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Motrin', 31);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Pepto-Bismol', 10);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Dramamine', 1);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Robitussin', 13);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Zyrtec', 10);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Pepto-Bismol', 16);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Pepto-Bismol', 9);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Aleve', 26);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Pepto-Bismol', 1);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Claritin', 28);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Allegra', 20);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Claritin', 12);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Dramamine', 3);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Allegra', 4);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Zantac', 38);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Tylenol', 17);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Tylenol', 35);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Benadryl', 37);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Mucinex', 6);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Benadryl', 27);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Benadryl', 39);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Zyrtec', 36);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Imodium', 35);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'DayQuil', 1);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Tylenol', 29);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'NyQuil', 20);
insert into nombre_medicamento (nombre_medicamento_id, nombre, medicamento_id) values (nombre_medicamento_seq.nextval, 'Aleve', 17);


Prompt insertando datos iniciales en presentacion_medicamento
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 418, 12);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 201, 21);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 395, 20);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 99, 38);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 53, 17);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 491, 9);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 460, 35);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 381, 10);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 471, 3);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 161, 37);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 170, 17);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 271, 33);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 415, 17);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 263, 5);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 319, 3);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 26, 11);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 179, 2);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 246, 28);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 81, 36);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 170, 1);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 167, 10);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 116, 2);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 9, 17);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 450, 11);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 199, 39);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 61, 12);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 120, 17);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 229, 39);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 300, 16);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 462, 19);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 73, 18);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 459, 37);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 71, 32);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 35, 22);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 39, 34);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 357, 7);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 321, 27);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 303, 35);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 408, 26);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 150, 22);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 357, 2);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 434, 33);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 5, 2);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 102, 9);
insert into presentacion_medicamento (presentacion_medicamento_id, cantidad, medicamento_id) values (presentacion_medicamento_seq.nextval, 162, 39);


Prompt insertando datos iniciales en empleado
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Vérane', 'Saddleton', 'Cottingham', TO_DATE('2022-11-14 03:40:31', 'YYYY-MM-DD HH24:MI:SS'), 'XDR0158715630');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Pélagie', 'Margery', 'Bullant', TO_DATE('2022-12-24 20:07:22', 'YYYY-MM-DD HH24:MI:SS'), 'IZE6672753998');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Kévina', 'Mailes', 'Jilliss', TO_DATE('2021-12-24 12:49:59', 'YYYY-MM-DD HH24:MI:SS'), 'PDG3912214559');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Táng', 'Basilone', 'Copcott', TO_DATE('2024-01-30 01:06:26', 'YYYY-MM-DD HH24:MI:SS'), 'UCQ9027520035');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Maëlys', 'Viel', 'Rimington', TO_DATE('2021-11-30 17:59:40', 'YYYY-MM-DD HH24:MI:SS'), 'JEJ4283741484');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Méthode', 'Northgraves', 'Morrison', TO_DATE('2021-07-27 10:04:59', 'YYYY-MM-DD HH24:MI:SS'), 'OXG3409483508');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Célia', 'Cuttles', 'Whitmell', TO_DATE('2024-03-22 14:47:06', 'YYYY-MM-DD HH24:MI:SS'), 'LDH4332587833');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Réjane', 'Yepiskov', 'Sprason', TO_DATE('2021-08-23 10:28:12', 'YYYY-MM-DD HH24:MI:SS'), 'GYB8568320748');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Ráo', 'Davidov', 'Scane', TO_DATE('2021-09-29 02:56:18', 'YYYY-MM-DD HH24:MI:SS'), 'ZUQ6079259869');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Réjane', 'Tenbrug', 'Younger', TO_DATE('2022-09-08 18:18:18', 'YYYY-MM-DD HH24:MI:SS'), 'CKQ5513465302');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Adélie', 'Markel', 'Drewery', TO_DATE('2021-06-07 14:30:18', 'YYYY-MM-DD HH24:MI:SS'), 'ZTM5038790179');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Almérinda', 'Dodswell', 'Maides', TO_DATE('2023-07-01 07:21:57', 'YYYY-MM-DD HH24:MI:SS'), 'NWJ7411726514');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Jú', 'McAne', 'Prayer', TO_DATE('2021-10-25 14:54:50', 'YYYY-MM-DD HH24:MI:SS'),'ZND6232124793');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Séverine', 'Cross', 'Rossetti', TO_DATE('2023-08-27 05:14:56', 'YYYY-MM-DD HH24:MI:SS'), 'KEJ5707638249');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Méthode', 'Borit', 'Bagnall', TO_DATE('2023-04-03 15:54:20', 'YYYY-MM-DD HH24:MI:SS'), 'DHX3352782142');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Danièle', 'Masser', 'Loughead', TO_DATE('2024-04-01 15:01:09', 'YYYY-MM-DD HH24:MI:SS'), 'ELB5470066766');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Eloïse', 'Clemmen', 'O'' Gara', TO_DATE('2023-10-25 12:26:14', 'YYYY-MM-DD HH24:MI:SS'), 'JAA6492556061');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Sòng', 'Robbins', 'Briiginshaw', TO_DATE('2024-03-04 03:30:40', 'YYYY-MM-DD HH24:MI:SS'), 'IHB6940573477');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Marie-françoise', 'Perks', 'Velden', TO_DATE('2023-04-10 08:42:23', 'YYYY-MM-DD HH24:MI:SS'), 'VKO9843734925');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Håkan', 'Lawly', 'Papaminas', TO_DATE('2024-04-12 05:45:12', 'YYYY-MM-DD HH24:MI:SS'), 'MZT0170319807');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Valérie', 'Scandrett', 'Bernadzki', TO_DATE('2021-10-12 08:30:16', 'YYYY-MM-DD HH24:MI:SS'), 'PGU6985813937');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Mélanie', 'Sheards', 'Hayzer', TO_DATE('2022-07-20 21:23:31', 'YYYY-MM-DD HH24:MI:SS'), 'XJS9164735931');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Cunégonde', 'Drescher', 'Buddington', TO_DATE('2024-01-25 06:24:30', 'YYYY-MM-DD HH24:MI:SS'), 'WHU6417768635');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Irène', 'Macak', 'Brayford', TO_DATE('2022-11-17 11:26:21', 'YYYY-MM-DD HH24:MI:SS'), 'PDA2633948471');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Méghane', 'Mays', 'Stoker', TO_DATE('2023-04-04 22:08:07', 'YYYY-MM-DD HH24:MI:SS'), 'NUD8143094364');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Håkan', 'Kenforth', 'Laughlan', TO_DATE('2022-09-22 12:16:38', 'YYYY-MM-DD HH24:MI:SS'), 'OQT1552682692');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Edmée', 'Dinkin', 'Boulde', TO_DATE('2021-07-21 11:43:16', 'YYYY-MM-DD HH24:MI:SS'), 'MQI9515041554');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Séréna', 'Isson', 'Pavis', TO_DATE('2024-01-03 13:03:18', 'YYYY-MM-DD HH24:MI:SS'), 'EQT9378198722');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Lyséa', 'Stenson', 'Sergean', TO_DATE('2023-09-22 21:32:47', 'YYYY-MM-DD HH24:MI:SS'), 'FBD0065481627');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Mélissandre', 'Bassingden', 'Fouldes', TO_DATE('2022-06-11 14:21:07', 'YYYY-MM-DD HH24:MI:SS'), 'DNH1846631678');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Nuó', 'Fairfoot', 'Zoellner', TO_DATE('2021-11-29 02:45:41', 'YYYY-MM-DD HH24:MI:SS'), 'LIS4328511554');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Marie-ève', 'Weathers', 'Bengal', TO_DATE('2021-11-13 12:05:48', 'YYYY-MM-DD HH24:MI:SS'), 'ONE6909512113');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Gisèle', 'Willishire', 'Rodgers', TO_DATE('2022-11-17 11:11:12', 'YYYY-MM-DD HH24:MI:SS'), 'NTT0814883540');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Léone', 'Rochell', 'Billam', TO_DATE('2024-02-19 22:52:00', 'YYYY-MM-DD HH24:MI:SS'), 'MUP8658224721');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Görel', 'Wimlett', 'Scorer', TO_DATE('2021-11-28 21:43:01', 'YYYY-MM-DD HH24:MI:SS'), 'GXW6667394501');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Marylène', 'Inchley', 'Janicijevic', TO_DATE('2024-04-22 04:58:40', 'YYYY-MM-DD HH24:MI:SS'), 'GPU4321582994');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Görel', 'McGirr', 'Nuzzi', TO_DATE('2024-02-04 06:50:05', 'YYYY-MM-DD HH24:MI:SS'), 'OEM2001360421');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Erwéi', 'Hallan', 'Bulford', TO_DATE('2023-06-12 15:02:48', 'YYYY-MM-DD HH24:MI:SS'), 'GBE6993733089');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Lóng', 'Walklot', 'Bader', TO_DATE('2021-05-06 09:44:52', 'YYYY-MM-DD HH24:MI:SS'), 'PHD5983585222');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Nélie', 'Hintzer', 'Busher', TO_DATE('2022-07-28 04:28:19', 'YYYY-MM-DD HH24:MI:SS'), 'SJQ2060003845');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Cécilia', 'Bromige', 'Leaves', TO_DATE('2022-01-27 16:22:56', 'YYYY-MM-DD HH24:MI:SS'), 'XJE4825308930');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Almérinda', 'Reye', 'Dartnall', TO_DATE('2021-09-16 10:17:35', 'YYYY-MM-DD HH24:MI:SS'), 'WYT5478245893');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Maïwenn', 'Floris', 'Berens', TO_DATE('2023-07-20 09:05:41', 'YYYY-MM-DD HH24:MI:SS'), 'XLF0496017215');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Cinéma', 'Vasichev', 'Ciobutaru', TO_DATE('2021-09-02 02:15:59', 'YYYY-MM-DD HH24:MI:SS'), 'OLN1025695039');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Bénédicte', 'Burree', 'Stolworthy', TO_DATE('2021-09-23 07:03:34', 'YYYY-MM-DD HH24:MI:SS'), 'GYM2233432666');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Aí', 'Beverage', 'Jephson', TO_DATE('2024-05-23 20:05:19', 'YYYY-MM-DD HH24:MI:SS'), 'BAH1158075778');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Léonore', 'Dewis', 'Cleveland', TO_DATE('2023-06-10 22:38:58', 'YYYY-MM-DD HH24:MI:SS'), 'EGG7992625272');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Josée', 'Drance', 'Whitehead', TO_DATE('2021-06-01 17:27:50', 'YYYY-MM-DD HH24:MI:SS'), 'KFC0996624917');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Mélia', 'Adel', 'Wyrill', TO_DATE('2021-10-02 03:35:05', 'YYYY-MM-DD HH24:MI:SS'), 'JRV4172212068');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Märta', 'Adamthwaite', 'Caudwell', TO_DATE('2021-10-31 05:29:10', 'YYYY-MM-DD HH24:MI:SS'), 'TWE8110105973');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Gérald', 'Mellows', 'Hawley', TO_DATE('2023-07-08 13:28:35', 'YYYY-MM-DD HH24:MI:SS'), 'BUD6049012065');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Méng', 'Marquess', 'Votier', TO_DATE('2023-07-03 10:46:53', 'YYYY-MM-DD HH24:MI:SS'), 'AUK8797013048');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Dù', 'McNickle', 'Sigward', TO_DATE('2023-04-05 15:25:09', 'YYYY-MM-DD HH24:MI:SS'), 'YRB8681148110');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Célestine', 'Twallin', 'MacLaig', TO_DATE('2023-04-10 00:24:12', 'YYYY-MM-DD HH24:MI:SS'), 'WED9368562722');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Nadège', 'Bromfield', 'Stebbings', TO_DATE('2022-12-10 06:48:51', 'YYYY-MM-DD HH24:MI:SS'), 'DXZ3551579636');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Maïlys', 'Bednall', 'Hillam', TO_DATE('2023-06-26 06:18:55', 'YYYY-MM-DD HH24:MI:SS'), 'XKF4429948593');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Méghane', 'Vasyutochkin', 'Manueau', TO_DATE('2023-04-19 22:11:51', 'YYYY-MM-DD HH24:MI:SS'), 'KJI5284285567');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Mélinda', 'Edgehill', 'Doche', TO_DATE('2022-07-01 17:14:27', 'YYYY-MM-DD HH24:MI:SS'), 'JXF9436622584');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Maëlla', 'Rivitt', 'Gibbon', TO_DATE('2023-05-30 23:48:47', 'YYYY-MM-DD HH24:MI:SS'), 'IDT4820515801');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Sòng', 'Klimkiewich', 'Debney', TO_DATE('2022-06-28 11:48:20', 'YYYY-MM-DD HH24:MI:SS'), 'FHG0652112144');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Lài', 'Oake', 'Gavagan', TO_DATE('2021-07-07 18:36:52', 'YYYY-MM-DD HH24:MI:SS'), 'KWK4032278337');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Maïlis', 'Spataro', 'Madre', TO_DATE('2023-05-13 12:20:17', 'YYYY-MM-DD HH24:MI:SS'), 'WGP3138063662');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Göran', 'Gait', 'Skentelbery', TO_DATE('2024-01-25 11:36:57', 'YYYY-MM-DD HH24:MI:SS'), 'XTD9846506156');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Réjane', 'Haylands', 'Cullingford', TO_DATE('2024-03-09 23:55:34', 'YYYY-MM-DD HH24:MI:SS'), 'MXX9381997009');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Léana', 'Clardge', 'Bemrose', TO_DATE('2021-06-21 00:17:36', 'YYYY-MM-DD HH24:MI:SS'), 'TXT2928886364');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Tán', 'Coils', 'Tompkin', TO_DATE('2022-01-15 07:21:45', 'YYYY-MM-DD HH24:MI:SS'), 'WCE6904055964');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Béatrice', 'Croci', 'Theaker', TO_DATE('2021-11-07 23:16:33', 'YYYY-MM-DD HH24:MI:SS'), 'YOJ4913962429');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Rachèle', 'Aldersley', 'Iacovino', TO_DATE('2024-04-25 12:09:45', 'YYYY-MM-DD HH24:MI:SS'), 'NZJ4235259429');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Kuí', 'Dunkerton', 'Oldrey', TO_DATE('2021-10-02 08:43:04', 'YYYY-MM-DD HH24:MI:SS'), 'UKM8935921095');
insert into empleado (empleado_id, nombre, apellido_paterno, apellido_materno, fecha_ingreso, rfc) values (empleado_seq.nextval, 'Adélie', 'Shorrocks', 'Wimlet', TO_DATE('2022-07-23 17:31:29', 'YYYY-MM-DD HH24:MI:SS'), 'ORZ6608213060');


Prompt insertando datos iniciales en centro de operaciones
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, '0Al9y4', 'Lowing', 'S5°93''0''''', 'E06°72''''89', '4467605352', 1, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'QE45Mx', 'Fone', 'N82°7''89''''', 'E64°00''''92', '5224428736', 0, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'Fq0eem', 'Dedmam', 'N33°4''5''''', 'E90°21''''59', '6456547047', 1, 0, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'XZ34or', 'Spurrier', 'N12°79''2''''', 'E23°13''''59', '8867117984', 1, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, '9xzEU5', 'Newcom', 'S1°52''53''''', 'W07°15''''48', '3057385971', 0, 0, 1);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'mP4qL9', 'Kindle', 'S20°33''05''''', 'E76°84''''17', '9058810054', 1, 0, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, '7s0I66', 'Twaits', 'N15°9''2''''', 'W55°49''''05', '1159348454', 1, 0, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'E5EtjN', 'Howcroft', 'N12°1''85''''', 'W30°34''''48', '4344288464', 0, 0, 1);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, '1MhFe4', 'Chaize', 'N6°86''3''''', 'W02°70''''67', '7896223430', 0, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'z47uE3', 'Borghese', 'S0°09''9''''', 'E08°18''''79', '8554724218', 1, 0, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'ZN50q7', 'Covell', 'N49°4''00''''', 'W90°42''''59', '2351006791', 0, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, '8FgI2R', 'Shoorbrooke', 'N7°8''5''''', 'W63°42''''04', '1176848959', 1, 0, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'ZI5Ft7', 'Canepe', 'N6°81''33''''', 'W77°28''''26', '4146014789', 1, 0, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'I23rso', 'Cardinal', 'N1°6''07''''', 'E31°25''''56', '8288205830', 0, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'HPxCNL', 'Feathersby', 'N76°5''3''''', 'W52°53''''48', '3712326414', 1, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'TOd0td', 'Dunmuir', 'N17°8''8''''', 'E81°65''''17', '9904628677', 0, 0, 1);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, '4HT0kK', 'Kovacs', 'N5°32''12''''', 'E15°46''''78', '3578663279', 1, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'u8Iv0x', 'Friedman', 'S4°47''43''''', 'E14°19''''02', '5646857024', 0, 0, 1);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'jGH5k0', 'McLarnon', 'N83°52''0''''', 'W36°37''''46', '4138174894', 0, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'c8VNN2', 'Kordovani', 'N7°50''56''''', 'E25°42''''17', '9642716029', 1, 0, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'PoQ5Wo', 'Bagg', 'N3°10''3''''', 'W86°56''''43', '8865360789', 0, 0, 1);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, '52gJoD', 'Muslim', 'S5°37''14''''', 'E69°27''''13', '7648925953', 1, 1, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'Jfmz50', 'Radloff', 'N4°4''9''''', 'E53°64''''36', '6223428267', 0, 0, 1);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, 'VJx7AQ', 'Boards', 'S5°8''54''''', 'W79°83''''70', '7252917371', 1, 0, 0);
insert into centro_operaciones (centro_operaciones_id, clave, direccion, latitud, longitud, telefono, es_farmacia, es_almacen, es_oficina) values (centro_operaciones_seq.nextval, '0aH7LH', 'Wyldish', 'S54°08''34''''', 'W20°38''''69', '2813698145', 0, 1, 0);

Prompt Insertando datos iniciales en almacen
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (1, 'C', 303949, empty_blob(), null);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (2, 'C', 180229, empty_blob(), null);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (4, 'D', 102297, empty_blob(), null);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (9, 'C', 453513, empty_blob(), null);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (11, 'D', 291677, empty_blob(), 1);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (14, 'C', 294223, empty_blob(), 2);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (15, 'C', 323726, empty_blob(), 4);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (17, 'M', 86654, empty_blob(), 9);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (19, 'D', 71749, empty_blob(), null);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (22, 'D', 327638, empty_blob(), null);
insert into almacen (centro_operaciones_id, tipo, capacidad, documento, almacen_contingencia_id) values (25, 'M', 446230, empty_blob(), null);

